CASMCMS-8290: Added vcs policy template
Cray-HPE/cray-kyverno-policies pull request #3
Opened 2022-11-21 17:58 UTC by rbak-hpe

## Summary and Scope

Adds a template for vcs/gitea

## Issues and Related PRs

* Resolves CASMCMS-8290
 
## Testing

Untested.  Not sure how to test this.

2023-02-02 11:08 UTC, jeremy-duckworth requested changes

2023-02-02 11:08 UTC, jeremy-duckworth commented on charts/kyverno-policies/templates/pod-sec-ctxt-vcs.yaml
> +{{- $name := "pod-sec-ctxt-vcs" }}
@rbak-hpe you can test how the policy modifies your deployment by using the `Kyverno CLI`. https://kyverno.io/docs/kyverno-cli/. You could also deploy this policy to a test system, and then restart your pods, etc.

2023-02-02 11:08 UTC, jeremy-duckworth commented on charts/kyverno-policies/templates/pod-sec-ctxt-vcs.yaml
> +{{- $name := "pod-sec-ctxt-vcs" }}
@rbak-hpe you'll want to pair this with a validation rule to keep the same convention as other policies here. Also, @mitchty has a PR in flight that re-arranges the directory structure a bit, FYI: https://github.com/Cray-HPE/cray-kyverno-policies/pull/4.

2023-06-24 00:04 UTC, yarlagadda-srinivasa-rao commented
As this is addressed in another PR. Closing this PR.

2023-06-24 00:04 UTC, closed without merging